# Generated by Django 4.1 on 2022-08-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='contry',
            new_name='country',
        ),
    ]
