# Generated by Django 4.1 on 2022-08-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contry_book_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Жанр'),
        ),
    ]
